### ISSUE TITLE
Error With Xcode 14

### ISSUE THREAD

**Issue by AlanFeiyang** [EmergeTools/ETTrace#25]
now use Xcode14.
when use -> Install the runner with brew install emergetools/homebrew-tap/ettrace
<img width="730" alt="image" src="https://user-images.githubusercontent.com/23370834/236717760-5fc71b92-f437-43b9-8de7-5e5a5446ddc6.png">

**Comment by noahsmartin** [comment]
The command line tools need to be installed, it looks like this message is coming from homebred not ettrace. Could you try running `xcode-select -p` and make sure it's pointing to the latest version of Xcode?

**Comment by noahsmartin** [comment]
Closing this since it appears to be unrelated to ETTrace, let us know if you're still experiencing the issue!
