### ISSUE TITLE
Symbol not found when linked to my project

### ISSUE THREAD

**Issue by denghuihua** [EmergeTools/ETTrace#30]
dyld[20258]: Symbol not found: (_objc_release_x20)
  Referenced from: '/private/var/containers/Bundle/Application/E0812C96-33A2-48DE-9DE3-A1FB0C93717B/TimeTesting.app/ETTrace.framework/ETTrace'
  Expected in: '/usr/lib/libobjc.A.dylib'
Symbol not found: (_objc_release_x20)
  Referenced from: '/private/var/containers/Bundle/Application/E0812C96-33A2-48DE-9DE3-A1FB0C93717B/TimeTesting.app/ETTrace.framework/ETTrace'
  Expected in: '/usr/lib/libobjc.A.dylib'

**Comment by Itaybre** [comment]
@denghuihua  Can you provide more information about the context where you ran the app?

Which Xcode version did you use?

**Comment by denghuihua** [comment]
After updating to swift package manger, these issues are gone
