### ISSUE TITLE
[Xcode 14.2] [Error] No member named 'emplace_back' in 'std::vector<Stack>'; did you mean '__emplace_back'

### ISSUE THREAD

**Issue by manojmahapatra** [EmergeTools/ETTrace#40]
Hi,

First of all thank you for the tool, caught my attention 😀, and thought to give it a spin. 

I added `ETTrace` as a SPM dependency in one of my projects from `main` branch (screenshot attached) as selecting exact latest version (`0.3.2`) ended up with package resolution error, and thus I switched to main branch and selected `ETTrace` lib. 

<img width="450" alt="Screenshot 2023-07-02 at 6 07 41 PM" src="https://github.com/EmergeTools/ETTrace/assets/2066984/9973278b-c7b5-41f2-ac36-362a226d4b22">

When I tried building my project, at this point I'm seeing a build error as - `No member named 'emplace_back' in 'std::vector<Stack>'; did you mean '__emplace_back'`. (Not entirely sure if this is specific to `x86_64` arch)

 I'm on Xcode 14.2 (14C18) running on macOS 13.4 (MBP 2019, Intel).  Cleaned build folder a couple of times, cleared derived data, restarted Xcode but to no avail. 
 
 Please let me know if I'm missing any steps.
 
Thank you,
Manoj

**Comment by Itaybre** [comment]
Hi,

This seems to be an issue with Xcode 14.2 (and earlier), in the last PR I made a fix for this: https://github.com/EmergeTools/ETTrace/pull/39/files#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677eR80

Unfortunately it is not merged yet. We are reviewing the previous Pull Requests.

**Comment by manojmahapatra** [comment]
@Itaybre thanks for the heads up. For now I created a `xcframework` and playing around with it. I'll keep an eye out when this PR gets merged.

**Comment by noahsmartin** [comment]
Hi @manojmahapatra the fix for this is now merged and included in v1.0.0
