### ISSUE TITLE
ETTrace error: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused"

### ISSUE THREAD

**Issue by sbsetting** [EmergeTools/ETTrace#41]
ETTrace error: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused"

When I enter "ettrace --launch --simulator", it show this error

**Comment by ahmdyasser** [comment]
@sbsetting  How did you solve this issue?

**Comment by Itaybre** [comment]
@ahmdyasser is your app running on the simulator?

**Comment by KevinHu2014** [comment]
At first I forgot to install ETTrace package on Xcode, and I see the error message as well.
