### ISSUE TITLE
emergetools.com flamegraph viewer freezes up

### ISSUE THREAD

**Issue by michaeleisel** [EmergeTools/ETTrace#47]
After making a recording on the simulator, and https://www.emergetools.com/flamegraph popping up, the site doesn't display any sort of flamegraph, and after a couple of seconds, it freezes up:

![](https://cdn.discordapp.com/attachments/1106667408804024452/1148993375203233944/Screenshot_2023-09-06_at_10.49.23_AM.png)

**Comment by noahsmartin** [comment]
Thanks for reporting @michaeleisel Are you using ettrace 1.0.0? We changed the format in that release, so the web processing is a bit different. We also just made some changes to https://www.emergetools.com/flamegraph that might help, can you check if it still reproduces?

**Comment by noahsmartin** [comment]
Closing with the new fixes to the site
