### ISSUE TITLE
Unable to link the xcframework to app or unable to add ETTrace as a Swift package

### ISSUE THREAD

**Issue by jadhav-sam** [EmergeTools/ETTrace#50]
1. Add ETTrace as a Swift package
 Here I unable see the package details and readme is also not loading.
<img width="459" alt="Screenshot 2023-09-15 at 5 05 16 PM (2)" src="https://github.com/EmergeTools/ETTrace/assets/66615521/c183022c-1cb3-4e3f-a689-4dfd2699bc9e">
<img width="1295" alt="Screenshot 2023-09-15 at 5 05 53 PM" src="https://github.com/EmergeTools/ETTrace/assets/66615521/d8301b3e-558c-4681-80a7-53ea41c017b9">
When tried multiple times, sometimes it also says that for PeerTalk could not find the feature/spm branch.

2. Link the xcframework to your app
Then I tried second approach. The framework that is generated is a folder and unable to add it.
<img width="411" alt="framework" src="https://github.com/EmergeTools/ETTrace/assets/66615521/df9b77fb-c9e2-427e-9c20-efe1d2d733fe">

<img width="589" alt="canNotAddFw" src="https://github.com/EmergeTools/ETTrace/assets/66615521/93deb757-23fa-42ab-84d1-afae71114884">

 Please help me to figure out how I can work with this. May be I am doing something wrong or missing few steps. Thanks

**Comment by Itaybre** [comment]
Have you tried using the SSH url instead of the HTTPS?
`git@github.com:EmergeTools/ETTrace.git`

**Comment by jadhav-sam** [comment]
Hi @Itaybre , Thank you for your reply. It is working now. Somehow it did not work when I was trying.

Currently I am getting below error: 
AppKit is not available when building for iOS. Consider using `#if canImport(AppKit)` to conditionally import this framework.


<img width="748" alt="Screenshot 2023-09-28 at 12 44 49 PM" src="https://github.com/EmergeTools/ETTrace/assets/66615521/277f71fb-6858-4817-a0bd-dcc91a8d70fa">
