### ISSUE TITLE
v1.0.0 tagged version is not semantic according to SPM

### ISSUE THREAD

**Issue by mkj-is** [EmergeTools/ETTrace#52]
The released version is tagged `v1.0.0` instead of `1.0.0` so it does not work correctly in Swift package manager. We are not able to specify other dependency rules than branch or exact commit.

<img width="237" alt="Screenshot 2023-09-21 at 14 22 13" src="https://github.com/EmergeTools/ETTrace/assets/708312/a39c8098-8787-47ed-8d09-74391244e53d">
<img width="1080" alt="Screenshot 2023-09-21 at 14 22 07" src="https://github.com/EmergeTools/ETTrace/assets/708312/ba1585a7-8a1e-43f2-82e1-3a6186d36824">

**Comment by noahsmartin** [comment]
It looks like the issue here was related to one of the dependencies not being pinned to a stable version. v1.0.1 should fix that with https://github.com/EmergeTools/ETTrace/pull/55 Thanks for reporting!

**Comment by mkj-is** [comment]
Works, thank you.
