### ISSUE TITLE
Key Not Found ("device")

### ISSUE THREAD

**Issue by rcrahul43** [EmergeTools/ETTrace#58]
ETTrace error: keyNotFound(CodingKeys(stringValue: "device", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"device\", intValue: nil) (\"device\").", underlyingError: nil))

I am using ETTrace version 1.0.0

**Comment by noahsmartin** [comment]
Hey @rcrahul43 can you double check that you are using 1.0.0 for both the framework in the app and the CLI? This error would be expected if there was a mismatch between the CLI and the framework
