### ISSUE TITLE
ETTrace error: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused"

### ISSUE THREAD

**Issue by NikolaGrujic91** [EmergeTools/ETTrace#59]
Error when trying to run `sudo ettrace --simulator`

![error](https://github.com/EmergeTools/ETTrace/assets/17230877/78c29a21-e335-4e16-b796-f35eba9cfd8a)

I have installed ettrace runner via
`brew install emergetools/homebrew-tap/ettrace`

I did not connect the ettrace to the app project via framework or swift package.

I am running on Xcode 15 and simulator is running on iOS 17

**Comment by noahsmartin** [comment]
Hey @NikolaGrujic91 this is expected if there is no app with ettrace installed running on the simulator, there is nothing to connect to. Please let us know if you have any issues when connecting to a simulator running an app with ettrace!

**Comment by ivancantarino** [comment]
I am encountering the exact same problem.
I had ETTrace running before, though now it doesn't work and throws the error described in this issue.

I have removed and re-added ETTrace once again as an SPM, rebooted everything, cleared SPM caches and Derived Data, uninstalled the app from the SIM and it keeps failing with that error.

Any hint on this issue?
Thanks.
