### ISSUE TITLE
ETTrace error: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused"

### ISSUE THREAD

**Issue by ivancantarino** [EmergeTools/ETTrace#65]
Hello 👋🏻 ,

After following all the instructions (installed ETTrace via SPM, installed locally through `brew`, etc), whenever I run the project and try to catch the data I get the error described in the image bellow. 

I have cleared all Xcode Derived Data, build folder, etc and re-added the package and always get the same error.  Any hint on how to surpass this issue, or am I missing something?

<img width="618" alt="Screenshot 2023-10-30 at 14 33 34" src="https://github.com/EmergeTools/ETTrace/assets/6607356/cb208705-2980-4188-a18b-8c7aa0a636d4">

**Comment by noahsmartin** [comment]
Hey @ivancantarino when you press return, is the app already running on your simulator? Do you see "Starting ETTrace" printed to the console of the app?

**Comment by ivancantarino** [comment]
@noahsmartin Yes, when I press `return` the app is already running in the simulator and the **"Starting ETTrace"** message is never shown in Terminal.

**Comment by noahsmartin** [comment]
Thanks for checking @ivancantarino "Starting ETTrace" is printed on app launch whenever the ettrace framework is linked to the app, even if you don't use the ettrace CLI. It sounds like your swift package isn't actually being linked into the app, try making sure you have added it as a dependency of the main app target, and remember to set it to "embed and sign"
![Screenshot 2023-11-01 at 2 42 14 PM](https://github.com/EmergeTools/ETTrace/assets/5882941/4d9d0ff4-12fb-44ce-a021-fc7ca93a2459)

**Comment by ivancantarino** [comment]
@noahsmartin great catch, that was indeed the issue. 
Resolved ✅
