### ISSUE TITLE
Doesn't Symbolicate System Libraries

### ISSUE THREAD

**Issue by michaeleisel** [EmergeTools/ETTrace#87]
The generated flamegraphs for my app don't symbolicate system library addresses. I see in the example that it does symbolicate them, but I don't see that in my output.

Steps to reproduce
- Install ETTrace with SwiftPM, embed the framework in y app
- Set the "Embed" setting for ETTrace to "Embed & Sign" (this doesn't seem to be mentioned in the instructions)
- Install the app to my physical phone
- Run `ettrace`
- Tap the app to open it
- Press Enter to begin profiling
- Press Enter to end profiling

iOS version: 17.2.1
Xcode version: 15.0

<img width="1007" alt="Screenshot 2024-08-05 at 4 47 11 PM" src="https://github.com/user-attachments/assets/7ff4bbd2-606d-44df-8ebb-9d3d62f6f285">

**Comment by noahsmartin** [comment]
Thanks for reporting @michaeleisel ! This is fixed in v1.1.0

**Comment by michaeleisel** [comment]
🎉
